eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8010/eureka/
spring:
 rabbitmq:
  host: crane.rmq.cloudamqp.com
  port: 5671
  username: zbgotrsf
  password: rH6WQwOWUlhVT86gNkmriuvTS-zBlHT8
  addresses: amqp://zbgotrsf:rH6WQwOWUlhVT86gNkmriuvTS-zBlHT8@crane.rmq.cloudamqp.com/zbgotrsf
management:
 security:
  enabled: false
  
---

spring:
 profiles: eureka
eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
server:
 port: 8010
---

spring:
 profiles: sendMS
server:
 port: 9020
zuul:
 routes:
  retreivalandsavems:
   path: /retreivalandsavems
  sendms:
   path: /sendms
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 120000   
---
spring:
 profiles: retreivalandsaveMS
 data:
  mongodb:
   uri: mongodb://ybhargava08:Earth2013@cluster0-shard-00-00-1na64.mongodb.net:27017,cluster0-shard-00-01-1na64.mongodb.net:27017,cluster0-shard-00-02-1na64.mongodb.net:27017/mymongoDB?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin 
server:
 port: 9010
limit: 5 
