eureka:
 client:
  serviceUrl:
   defaultZone: https://ybeurekaserver.cfapps.io/eureka/
spring:
 rabbitmq:
  host: crane.rmq.cloudamqp.com
  port: 5671
  username: zbgotrsf
  password: rH6WQwOWUlhVT86gNkmriuvTS-zBlHT8
  addresses: amqp://zbgotrsf:rH6WQwOWUlhVT86gNkmriuvTS-zBlHT8@crane.rmq.cloudamqp.com/zbgotrsf
hystrix:
 threadpool.default.coreSize: "20"
 threadpool.default.maxQueueSize: "500000"
 threadpool.default.keepAliveTimeMinutes: "2"
 threadpool.default.queueSizeRejectionThreshold: "500000"
 command:
   default:
     fallback.isolation.semaphore.maxConcurrentRequests: "20"
     execution:
       timeout:
         enabled: "false"
#       isolation:
#         strategy: "THREAD"
#         thread:
#           timeoutInMilliseconds: "30000"
ribbon:
 ReadTimeout: 100000
 ConnectTimeout: 100000
management:
 security:
  enabled: false 
---

spring:
 profiles: eureka
eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
#server:
 #port: 8010
---

spring:
 profiles: sendMSLocal
 resources:
  static-locations: file:///C:/Users/ybhargava08/git/springcloudrep/springCloudRestClient/SendMS/src/main/resources/static/
  cache-period: 0
 mvc:
  view:
   prefix: /resources/static/
   suffix: .html
server:
 port: 9020
eureka:
 instance:
  hostname: 192.168.99.100
  secure-port-enabled: false
  non-secure-port-enabled: true
  health-check-url: http://${eureka.instance.hostname}:${server-port}/health
  status-page-url: http://${eureka.instance.hostname}:${server-port}/info
  home-page-url: http://${eureka.instance.hostname}:${server-port}/ 
zuul:
 routes:
  retreivalandsavems:
   path: /retreivalandsavems
  sendms:
   path: /sendms
logging:
 level:
  org:
   springframework:
    web: DEBUG
 file: C:\Users\ybhargava\Desktop\springcloudtest_jars\logs\sendms.log
---
spring:
 profiles: sendMS
 mvc:
  view:
   prefix: /resources/static/
   suffix: .html
zuul:
 routes:
  retreivalandsavems:
   path: /retreivalandsavems
  sendms:
   path: /sendms
eureka:
 instance:
  hostname: sendms.cfapps.io
  secure-port-enabled: true
  non-secure-port-enabled: false
  secure-port: 443
  health-check-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/health
  status-page-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/info
  home-page-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/
   
---
spring:
 profiles: retreivalandsaveMS
 data:
  mongodb:
   uri: mongodb://ybhargava08:yash635@mymongocluster-shard-00-00-nmxff.mongodb.net:27017,mymongocluster-shard-00-01-nmxff.mongodb.net:27017,mymongocluster-shard-00-02-nmxff.mongodb.net:27017/test?ssl=true&replicaSet=MyMongoCluster-shard-0&authSource=admin
limit: 5
eureka:
 instance:
  hostname: retreiveandsavems.cfapps.io
  secure-port-enabled: true
  non-secure-port-enabled: false
  secure-port: 443
  health-check-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/health
  status-page-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/info
  home-page-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}/
useTST: true
---
spring:
 profiles: retreivalandsaveMSLocal
 data:
  mongodb:
   uri: mongodb://192.168.99.100:27017/db
limit: 5
server:
 port: 9010
eureka:
 instance:
  hostname: 192.168.99.100
  secure-port-enabled: false
  non-secure-port-enabled: true
  health-check-url: http://${eureka.instance.hostname}:${server-port}/health
  status-page-url: http://${eureka.instance.hostname}:${server-port}/info
  home-page-url: http://${eureka.instance.hostname}:${server-port}/
useTST: true
---
spring:
 profiles: zipkinserver
server:
 port: 9411
